"""add file_name and thumbnail_name to content

Revision ID: 1ce55a14588c
Revises: h7i8j9k0l1m2
Create Date: 2026-06-27 21:54:25.228224
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ce55a14588c'
down_revision: Union[str, None] = 'h7i8j9k0l1m2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: removed auto-generated drop_table('device_tokens') — table is needed for push notifications
    # NOTE: removed auto-generated drop_constraint('audit_logs_admin_id_fkey') — FK is needed
    op.add_column('content', sa.Column('file_name', sa.String(length=300), nullable=True))
    op.add_column('content', sa.Column('thumbnail_name', sa.String(length=300), nullable=True))
    op.alter_column('system_notification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_notification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('content', 'thumbnail_name')
    op.drop_column('content', 'file_name')
    op.create_foreign_key(op.f('audit_logs_admin_id_fkey'), 'audit_logs', 'admin_users', ['admin_id'], ['id'])
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('device_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('uq_device_tokens_token'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_active'), 'device_tokens', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###
